default_icon = '*'
remove_duplicates = false
enable_rename = true

[[icons]]
alacritty= 'terminal'
atom= 'code'
banshee= 'play'
blender= 'cube'
chromium= 'chrome'
cura= 'cube'
darktable= 'image'
discord= 'comment'
eclipse= 'code'
emacs= 'code'
eog= 'image'
evince= 'file-pdf'
evolution= 'envelope'
feh= 'image'
file-roller= 'compress'
filezilla= 'server'
firefox= 'firefox'
firefox-esr= 'firefox'
gimp= 'image'
"gimp-2.8"= 'image'
gnome-control-center= 'toggle-on'
gnome-terminal-server= 'terminal'
google-chrome= 'chrome'
prusa-slicer= 'cube'
gpick= 'eye-dropper'
imv= 'image'
insomnia= 'globe'
java= 'code'
jetbrains-idea= 'code'
jetbrains-studio= 'code'
keepassxc= 'key'
keybase= 'key'
kicad= 'microchip'
kitty= 'terminal'
libreoffice= 'file-alt'
"lua5.1"= 'moon'
mpv= 'tv'
mupdf= 'file-pdf'
mysql-workbench-bin= 'database'
nautilus= 'copy'
nemo= 'copy'
openscad= 'cube'
pavucontrol= 'volume-up'
postman= 'space-shuttle'
rhythmbox= 'play'
robo3t= 'database'
signal= 'comment'
slack= 'slack'
"slic3r.pl"= 'cube'
spotify= 'music'
steam= 'steam'
subl= 'file-alt'
subl3= 'file-alt'
sublime_text= 'file-alt'
thunar= 'copy'
thunderbird= 'envelope'
totem= 'play'
urxvt= 'terminal'
xfce4-terminal= 'terminal'
xournal= 'file-alt'
yelp= 'code'
zenity= 'window-maximize'
zoom= 'comment'
jetbrains-idea-ce= 'java'
DBeaver= 'database'
code= 'file'
Code= 'file'
"trello desktop"= 'file'
guake= 'terminal'
terminator= 'terminal'